# Generated by Django 4.1 on 2022-08-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('Cafe', '카페'), ('StudyRoom', '스터디룸'), ('Etc', '기타')], max_length=10)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('wifi', models.CharField(choices=[('Fast', '빠름'), ('Slow', '느림'), ('No', '없음')], max_length=5)),
                ('power_socket', models.CharField(choices=[('Many', '많음'), ('Average', '보통'), ('Less', '적음'), ('No', '없음')], max_length=10)),
                ('rating', models.FloatField()),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
        ),
    ]
